Assignments/tic tac toe
bhs-intro-to-programming/becksmoreland pull request #10
Opened 2022-11-15 23:05 UTC by becksmoreland

2022-11-17 17:11 UTC, gigamonkey requested changes
This is a reasonable start. You should keep going.

2022-11-17 17:11 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +    if ((playerOne + 2) % 2 === 0) {
Not sure what the + 2 is doing here. (x + 2) % 2 === x % 2 for all positive x. (That it's not the same for negative x is a kind of esoteric detail of Javascript but doesn't seem relevant here.)

2022-11-17 17:11 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +      playerOne.current === 'X'
The use of `currentLetter`, `playerOne`, *and* `playerOne.current` is kinda confused. I assume you're still working on this.

2022-12-09 22:43 UTC, becksmoreland commented
Made some changes, don't know why some of the box checks don't work, think it might be triggering one only.

2022-12-11 18:11 UTC, gigamonkey requested changes
I mentioned this in one of the comments but you should probably take a look at this video I made for an explanation of some ideas that will help you with this code: https://www.youtube.com/watch?v=ez8FRoBIuuM

2022-12-11 18:11 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +  }
So this is always drawing the mark at the raw x,y coordinate where the player clicked, which may or may not be positioned properly in the board. The way I'd think about it is: translate the raw x, y to a row/column coordinate (where rows and columns are both 0, 1, or 2) and then draw the mark at the right place on the board for the given row/column.

2022-12-11 18:11 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +};
You should try to get rid of almost all these literal numbers (`150`, `400`, `200`, `100`, etc.; the `3` in `/ 3`, however, is okay) and instead compute all the coordinates in terms of `width` and `height`. On my screen this code draws a very mangled board.

2022-12-11 18:11 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +    currentPos[1][1] = 'X';
Remember that array indices are 0-based. So the index of the first column of the first row is `[0][0]` not `[1][1]`.

2022-12-11 18:11 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +  if ((x < width / 3) && (y > height / 3 - 20)) {
This chain of `if`/`else`s is roughly speaking what I was talking about above about translating raw x,y coordinates into row/col coordinates that you can use as indices into the `currentPos` array. But you've got a bunch of hardwired numbers in here similar to the ones I commented on in your `ticTacToeBoard` function that are making this more complicated than it needs to be. The pattern should be very regular, assuming your board is either basically square or, alternatively, covers the whole drawing area. Eventually you should be able to distill the pattern down to some simple math but it can be useful to write it out as logic first. (You can watch this video I made analyzing another student's code for some more about this: https://www.youtube.com/watch?v=ez8FRoBIuuM)

2023-01-03 22:55 UTC, merged