Assignments/chess board
bhs-intro-to-programming/becksmoreland pull request #6
Opened 2022-10-31 22:27 UTC by becksmoreland

2022-10-31 22:29 UTC, becksmoreland commented
Just drew the characters and represented the board as an array, no interactive stuff yet.

2022-11-02 23:52 UTC, gigamonkey requested changes
Thanks for posting a PR . I left a couple comments of things for you to think about as you keep working on this.

2022-11-02 23:52 UTC, gigamonkey commented on assignments/chess-board/code.js
> +const wKing = () => {
These functions are kind of promising but it seems like if they're going to be responsible for drawing the piece on the board they should take arguments that specify a square on the board, such as a row and column coordinate. If the argument is in terms of the chess board (like, 0,0 is the top left square and 7,7 is the bottom right) then these functions can be responsible for translating that to the right coordinates in the graphical coordinate system to draw the text at the right place.

2022-11-02 23:52 UTC, gigamonkey commented on assignments/chess-board/code.js
> +  [bRook(200)], [bKnight(150)], [bBishop(100)], [bQueen(50)], [bKing()], [bBishop(- 50)], [bKnight(- 100)], [bRook(-150)],
This is a bit odd as those functions all return `undefined` so putting the result of calling the function in the array representing the board doesn't really make sense.

2022-12-02 23:26 UTC, becksmoreland commented
I just updated it and used objects to collect the chess pieces instead of having a single CONST function for every piece and sorting them into two functions.

2022-12-05 22:51 UTC, becksmoreland commented
@gigamonkey Hey look at this one for my use of Objects and Organizing

2022-12-06 03:33 UTC, gigamonkey requested changes
This is going in a good direction. The initial use of objects is a good start but there are some even better opportunities to really use objects to good effect in this program which we can talk about in class.

2022-12-06 03:33 UTC, gigamonkey commented on assignments/chess-board/code.js
> +const whitePieces = {'WhiteKing' : '♔', 'WhiteQueen' : '♕', 'WhiteRook' : '♖', 'WhiteBishop' : '♗', 'WhiteKnight' : '♘', 'WhitePawn' : '♙'}
This is nice. You should try making these two objects have the same properties, i.e. just use the piece names so you have two objects with `king`, `queen`, `rook`, `bishop`, `knight`, and `pawn` properties, one containing the characters for the black pieces and one for the white.

2022-12-06 03:33 UTC, gigamonkey commented on assignments/chess-board/code.js
> +  [wRook(146), wKnight(110), wBishop(70), wQueen(34), wKing(- 5), wBishop(- 40), wKnight( - 75), wRook( - 115)]
This is a little weird since all the functions you use here return `undefined` since they just call `drawText` for side effect and return nothing explicitly. What  would be neat would be to make objects to represent the specific pieces and then move those around in the board array. Let's try to find some time to talk about that tomorrow, probably with you and some other students who aren't reviewing for the next assessment.

2022-12-09 22:42 UTC, becksmoreland commented
Working on fixing the things you mentioned in the comments but a little confused with the 2D array. Messed around with the positioning of the pieces.

2022-12-11 17:53 UTC, gigamonkey requested changes
Left you a suggestion of something to work on.

2022-12-11 17:53 UTC, gigamonkey commented on assignments/chess-board/code.js
> +const wPawn = (space) => {
All these functions are a bit odd since they hard wire a particular y position for the piece. But eventually you need to be able to draw any piece on any square of the board. Can you provide an implementation of this function:

```javacript
// Draw the named piece with the right character at the given row and column
const drawPiece = (name, color, row, col) => {
  // your code here
}
```

It would be called like `drawPiece('King', blackPieces, 0, 4)`. Recall that you can access object properties with `[]` as well as the `.` So in the function above the expression `color[name]` would access the character of the named piece out of the object (either `blackPieces` or `whitePieces` passed as the `color` argument.

Anyway, play around with that and if you get stuck ask for help. Once you have that in place, then we can talk about how to use the 2d array to represent the board.

2023-01-03 22:56 UTC, merged