Assignments/string functions
bhs-intro-to-programming/becksmoreland pull request #7
Opened 2022-10-31 22:28 UTC by becksmoreland

2022-10-31 22:29 UTC, becksmoreland commented
Not done yet, don't know how to stop the index for the last character for beginning ones.

2022-11-02 21:14 UTC, gigamonkey requested changes
Except for the one function I commented on this all looks right. And you are one of the few students to use `[]` when appropriate so nice job on that. Why don't you try to fix `stringContains` and then request another review.

2022-11-02 21:14 UTC, gigamonkey commented on assignments/string-functions/code.js
> +  return string2 === string1.substring(string1.indexOf(string2));
This is not quite right. It works when `string2` is at the end of `string1` but not if it's somewhere else. One of the test cases tests things calling `stringContains("foobar", "foo")` which should be `true` but this returns `false`.

Can you try to fix this?

2022-11-05 04:28 UTC, gigamonkey requested changes
Just one you didn't get quite right. I gave you a hint. Can you fix it and request another review.

2022-11-05 04:28 UTC, gigamonkey commented on assignments/string-functions/code.js
> +  return string2 === string1.substring(string1.indexOf(string2), string1.indexOf(string2) + string2.length);
This is almost right but you need to account for the case that `string2` isn't present in which case `indexOf` return -1 which will probably blow up `substring` since -1 isn't a legal index. And this is too complicated. You can use the fact that `indexOf` returns a specific value when the argument string is not found to directly translate into the boolean we want. Can you try to figure out how?

2022-11-05 04:28 UTC, gigamonkey commented on assignments/string-functions/code.js
> +  return string[string.length - 1].toUpperCase() + string[string.length - 1].toLowerCase();
This is correct and fine. Worth noting though that since you already wrote `upDown` you could use it here:

```javascript
return upDown(string[string.length - 1]);
```

2022-12-09 22:53 UTC, becksmoreland commented
I'm done with this one, can you approve?

2022-12-10 01:23 UTC, gigamonkey approved these changes
Great. Ship it!

2022-12-13 03:30 UTC, merged